version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somezoneminder
       MYSQL_USER: zoneminder
       MYSQL_PASSWORD: zoneminder

   zoneminder:
     depends_on:
       - db
     image: texasaggie97/zoneminder:latest
     ports:
       - "8088:80"
     restart: always
     environment:
       ZM_DB_ROOT_PASSWORD: somezoneminder
       ZM_DB_HOST: db
       ZM_DB_USER: zoneminder
       ZM_DB_PASSWORD: zoneminder
       TZ: America/Chicago
volumes:
    dbdata:


